apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-05-08T10:40:03Z"
  generation: 1
  labels:
    app: tuto-api
  name: tuto-api
  namespace: nicolas
  resourceVersion: "563003"
  selfLink: /apis/extensions/v1beta1/namespaces/nicolas/deployments/tuto-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tuto-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tuto-api
    spec:
      containers:
      - image: nicodeur/k8s-api:latest
        imagePullPolicy: Always
        name: k8s-api
        env:
        - name: MYSQL_HOST
          value: tuto-bdd
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: MYSQL_DATABASE
          value: workshop
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-05-08T10:40:03Z"
    lastUpdateTime: "2020-05-08T10:40:14Z"
    message: ReplicaSet "tuto-api-75c5767ff4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-05-08T10:40:47Z"
    lastUpdateTime: "2020-05-08T10:40:47Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
